package CORBAImplementation;


/**
* CORBAImplementation/CORBAImplementation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBAImplementation.idl
* Friday, June 15, 2018 4:13:15 o'clock PM EDT
*/

public interface CORBAImplementation extends CORBAImplementationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CORBAImplementation
