package CORBAImplementation;

/**
* CORBAImplementation/CORBAImplementationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from idl
* Friday, June 15, 2018 4:13:15 o'clock PM EDT
*/

public final class CORBAImplementationHolder implements org.omg.CORBA.portable.Streamable
{
  public CORBAImplementation value = null;

  public CORBAImplementationHolder ()
  {
  }

  public CORBAImplementationHolder (CORBAImplementation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = CORBAImplementationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    CORBAImplementationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return CORBAImplementationHelper.type ();
  }

}
